"""
Daily Report Generator — Generates daily summary reports.
"""

import json
import os
import sqlite3
import time
from datetime import datetime


def generate_daily_report(reports_dir: str = "reports", db_path: str = "logs/monitor.db") -> str:
    """Generate a daily summary report from all audits performed today."""
    today = datetime.now().strftime("%Y-%m-%d")
    today_dir = os.path.join(reports_dir, today)

    if not os.path.isdir(today_dir):
        return f"# Daily Report — {today}\n\nNo audits performed today.\n"

    # Load all JSON summaries
    summaries = []
    for f in sorted(os.listdir(today_dir)):
        if f.endswith(".json"):
            with open(os.path.join(today_dir, f)) as jf:
                summaries.append(json.load(jf))

    if not summaries:
        return f"# Daily Report — {today}\n\nNo audits performed today.\n"

    # Aggregate stats
    total_audits = len(summaries)
    total_tokens = sum(s.get("total_tokens", 0) for s in summaries)
    severity_totals = {"CRITICAL": 0, "HIGH": 0, "MEDIUM": 0, "LOW": 0, "INFO": 0}
    chains = {}

    for s in summaries:
        chain = s.get("chain", "unknown")
        chains[chain] = chains.get(chain, 0) + 1
        for sev, count in s.get("severities", {}).items():
            severity_totals[sev] = severity_totals.get(sev, 0) + count

    # Top contracts by findings
    top_contracts = sorted(summaries, key=lambda s: s.get("findings_count", 0), reverse=True)[:10]

    report = f"""# 📊 SmartAudit Monitor — Daily Report

**Date:** {today}
**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

---

## Summary

| Metric | Value |
|--------|-------|
| Total Audits | {total_audits} |
| Total Tokens Used | {total_tokens:,} |
| Avg Tokens/Audit | {total_tokens // max(1, total_audits):,} |
| Chains Monitored | {len(chains)} |

### Chains
"""
    for chain, count in sorted(chains.items(), key=lambda x: x[1], reverse=True):
        report += f"- **{chain}**: {count} contracts audited\n"

    report += f"""
### Findings by Severity

| Severity | Count |
|----------|-------|
| 🔴 CRITICAL | {severity_totals['CRITICAL']} |
| 🟠 HIGH | {severity_totals['HIGH']} |
| 🟡 MEDIUM | {severity_totals['MEDIUM']} |
| 🟢 LOW | {severity_totals['LOW']} |
| ℹ️ INFO | {severity_totals['INFO']} |

---

## Top Contracts by Findings

"""
    for i, s in enumerate(top_contracts, 1):
        sev_str = " | ".join(f"{k}: {v}" for k, v in s.get("severities", {}).items() if v > 0)
        report += (
            f"### {i}. {s.get('contract_name', 'Unknown')} (`{s.get('address', '')[:10]}...`)\n"
            f"- **Chain:** {s.get('chain')}\n"
            f"- **Findings:** {s.get('findings_count', 0)} ({sev_str})\n"
            f"- **Tokens:** {s.get('total_tokens', 0):,}\n"
            f"- **Duration:** {s.get('duration_ms', 0)/1000:.1f}s\n\n"
        )

    report += f"""---

## Token Usage

- **Total consumed today:** {total_tokens:,} tokens
- **Estimated cost:** ~${total_tokens * 0.000002:.2f} (at MiMo pricing)
- **Audits per token budget (1M):** ~{1_000_000 // max(1, total_tokens // max(1, total_audits))} audits

---

*Generated by SmartAudit Monitor v2.0 — Powered by Xiaomi MiMo V2.5*
"""

    # Save report
    report_path = os.path.join(reports_dir, f"daily_{today}.md")
    with open(report_path, "w") as f:
        f.write(report)

    return report
